apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: kargo-demo-ing
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: prod.7f000001.nip.io
