---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionTemplate:
    spec:
      vars:
      - name: targetBranch
        value: dev
      steps:
      - task:
          name: default-promote
        as: promote-to-dev
