apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/christianh814/kargo-demo-deploy
      writeBranch: env/dev
      render: {}
    argoCDAppUpdates:
    - appName: dev-app
