apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-promotionpolicy.yaml
- dev-stage.yaml
- ns.yaml
- prod-stage.yaml
- produsw1-stage.yaml
- produsw2-stage.yaml
- test-stage.yaml
- uat-promotionpolicy.yaml
- uat-stage.yaml
