apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- warehouse-demo.yaml
- dev-stage.yaml
- test-stage.yaml
- uat-stage.yaml
- produsw1-stage.yaml
- produsw2-stage.yaml
- simple-analysistemplate.yaml
- kargo-ing.yaml

sortOptions:
  order: fifo
