apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- dev-stage.yaml
- kargo-ing.yaml
- produsw1-stage.yaml
- produsw2-stage.yaml
- project.yaml
- simple-analysistemplate.yaml
- test-stage.yaml
- uat-stage.yaml
- warehouse-demo.yaml
