---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: sky
spec:
  subscriptions:
    upstreamStages:
      - name: uat
