---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: produsw2
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: red
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: produsw2-app
