---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: produsw2
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: produsw2-app
    gitRepoUpdates:
    - repoURL: https://github.com/christianh814/kargo-demo-deploy
      writeBranch: env/produsw2
      render: {}
