---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: produsw1
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: purple
spec:
  subscriptions:
    upstreamStages:
      - name: prod
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: produsw1-app
