apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - dev
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionTemplate:
     spec:
       steps:
       - uses: git-clone
         config:
           repoURL: https://github.com/christianh814/kargo-demo-deploy
           checkout:
           - branch: main
             path: ./main
           - branch: env/test
             create: true
             path: ./test
       - uses: kustomize-set-image
         as: update-image
         config:
           path: ./main/app/overlays/test
           images:
           - image: ghcr.io/christianh814/kargo-demo-app
       - uses: kustomize-build
         config:
           path: ./main/app/overlays/test
           outPath: ./app/manifests.yaml  
       - uses: git-clear
         config:
           path: ./test/
       - uses: git-commit
         as: commit
         config:
           path: ./test
           messageFromSteps:
           - update-image
       - uses: git-push
         config:
           path: ./test
           targetBranch: env/test
       - uses: argocd-update
         config:
           apps:
           - name: test-app
             namespace: argocd
             sources:
             - repoURL: https://github.com/christianh814/kargo-demo-deploy
               desiredCommitFromStep: commit
