apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - dev
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionTemplate:
    spec:
      vars:
      - name: targetBranch
        value: test
      steps:
      - task:
          name: default-promote
        as: promote-to-test
