apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/christianh814/kargo-demo-deploy
      writeBranch: env/test
      render: {}
    argoCDAppUpdates:
    - appName: test-app
