apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: lime
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionTemplate:
     spec:
       steps:
       - uses: git-clone
         config:
           repoURL: https://github.com/christianh814/kargo-demo-deploy
           checkout:
           - branch: main
             path: ./main
           - branch: env/uat
             create: true
             path: ./uat
       - uses: kustomize-set-image
         as: update-image
         config:
           path: ./main/app/overlays/uat
           images:
           - image: ghcr.io/christianh814/kargo-demo-app
       - uses: kustomize-build
         config:
           path: ./main/app/overlays/uat
           outPath: ./app/manifests.yaml  
       - uses: git-overwrite
         config:
           inPath: ./app
           outPath: ./uat/
       - uses: git-commit
         as: commit
         config:
           path: ./uat
           messageFromSteps:
           - update-image
       - uses: git-push
         config:
           path: ./uat
           targetBranch: env/uat
           generateTargetBranch: true
       - uses: argocd-update
         config:
           apps:
           - name: uat-app
             namespace: argocd
             sources:
             - repoURL: https://github.com/christianh814/kargo-demo-deploy
               desiredCommitFromStep: commit
