apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: lime
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  verification:
    analysisTemplates:
    - name: kargo-demo
  promotionTemplate:
    spec:
      vars:
      - name: targetBranch
        value: uat
      steps:
      - task:
          name: default-promote
        as: promote-to-uat
