apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/christianh814/kargo-demo-deploy
      branch: main
      commitSelectionStrategy: SemVer
      allowTags: '^v\d+\.\d+\.\d+$'
      semverConstraint: '>= 1.2.3'
  - image:
      repoURL: ghcr.io/christianh814/kargo-demo-app
      imageSelectionStrategy: SemVer
      allowTags: '^v\d+\.\d+\.\d+$'
      semverConstraint: '>= 1.2.3'
