apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/christianh814/kargo-demo-deploy
      revision: HEAD
      directories:
      - path: app/overlays//*
  template:
    metadata:
      name: '{{path.basename}}-app'
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{path.basename}}
    spec:
      project: default
      source:
        repoURL: https://github.com/christianh814/kargo-demo-deploy
        targetRevision: env/{{path.basename}}
        path: app # default for bookkeeper
      destination:
        name: in-cluster
        namespace: '{{path.basename}}-app'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
